FROM node:14.4.0-alpine

ENV LANG=C.UTF-8 \
  TZ=Asia/Tokyo \
  HOST=0.0.0.0 \
  PORT=3000 \
  SRC_DIR=/frontend/tsundoku-nuxt

WORKDIR $SRC_DIR
ADD ./frontend/tsundoku-nuxt $SRC_DIR

RUN apk update \
  && apk upgrade \
  && apk add --no-cache bash \
  && npm install -g nuxt \
  && yarn add --dev @nuxtjs/eslint-module
