version: '3'

services:
  api:
    build: .
    ports:
      - 8080:8080
      - 2345:2345
    depends_on:
      - db
    volumes:
      - ./api:/go/1.15.2/src/github.com/ham357/tsundoku/api
    tty: true
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: tsundoku
      USER_NAME:
      USER_ID:
      GROUP_NAME:
      GROUP_ID:
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE

  front_end:
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - 3000:3000
    command: yarn run dev
    volumes:
      - ./frontend/tsundoku-nuxt:/frontend/tsundoku-nuxt
      # exclude volumes
      - /frontend/tsundoku-nuxt/node_modules
    tty: true
    depends_on:
      - api
      - db

  db:
    image: mysql:5.7
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_DATABASE: tsundoku
    ports:
      - "4444:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
