version: '3'

services:
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./api:/go/1.15.2/src/github.com/ham357/tsundoku/api
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: tsundoku

  db:
    image: mysql:5.7
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_DATABASE: tsundoku
    ports:
      - "4444:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
